# Generated by Django 3.0.5 on 2020-04-15 20:39

from django.db import migrations
import csv


class Migration(migrations.Migration):

    dependencies = [
        ('golfer', '0003_add_golfer_city'),
    ]
    
    def add_city_data (apps, schema_editor):
        try:
            filename = "golfersInput.csv"
            # Create file object and open
            input_file = open(filename, 'r')
        
            # Call reader function of csv module, pass it to the File object
            file_lines = csv.reader(input_file)
        
            #  Create golfers list, pass csvReader object
            golfers_list = list(file_lines)
        
            # Use for loop to traverse nested list
            for name, birthdate, city in golfers_list:
                # Take golfer name, birthdate, and city, stripped of whitespace
                name.strip()
                birthdate.strip()
                city.strip()
            # Close input file
            input_file.close()
        except IOError:
            print("File not Found Error")
        
        Golfer = apps.get_model('golfer', 'Golfer')
        for name, bdate, city in golfers_list:
            # Retrieve golfer object using model manager get method
            golfer = Golfer.objects.get(golfer_name=name)
            # Get golfer_city attribute and set it
            golfer.golfer_city=city
            # Save the new data
            golfer.save()

    def remove_city_data (apps, schema_editor):
        # Get Golfer model 
        Golfer = apps.get_model('golfer', 'Golfer')
        Golfer.objects.update(golfer_city='unknown')
        
    operations = [
        migrations.RunPython(add_city_data, 
                            reverse_code=remove_city_data)
    ]
